### ISSUE TITLE
Incomplete WSDL files for XDS

### ISSUE THREAD

**Issue by jkiddo** [IHE/IT-Infrastructure#1]
The XDS wsdl files are 'incomplete' as they refer to xsd files not located in this respository

**Comment by organsnyder** [comment]
For anyone trying to get these to work: I downloaded the schema directory from the IHE FTP site and put it in the repo root directory: ftp://ftp.ihe.net/TF_Implementation_Material/ITI/schema

That got the WSDLs working in SoapUI.

**Comment by JohnMoehrke** [comment]
is there a recommended fix? Please submit a pull request. If you can't submit a pull request let me know. We are trying to use this repository to learn how to use GIT for committee work.

**Comment by ppazos** [comment]
@JohnMoehrke did you see the PR sent by @organsnyder ?

**Comment by JohnMoehrke** [comment]
I now see it. My failure. I am learning github... 
So, I am not a wsdl expert... I am not the authority on these... But I will check with Steve and try to get Bill to review these first. Not that this approval would have been done with FTP, but rather as an exercise in leveraging process because github enables a process.

**Comment by JohnMoehrke** [comment]
@stl-steve-moore can you look at these wsdl, and/or have Bill look at them?

**Comment by jkiddo** [comment]
... and you guys have to work on your latency

**Comment by JohnMoehrke** [comment]
Yes indeed. Learning as we go. Would like if others looked at the pull
request and added their endorsement. Collaboration is good.

**Comment by JohnMoehrke** [comment]
in the absence of someone capable to review these, I simply accepted the merge pull.
