### ISSUE TITLE
IUA Cross Profile Consideration

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/IT-Infrastructure#102]
The first bullet in section 34.6 states that the XUA profile defines a transaction to retrieve a SAML2 assertion.
That is not entirely true in my opinion... XUA profile does not define a transaction, it only says that a transaction to retrieve a SAML2 token should exist but it is not profiled because it is left as a project specific implementation.

**Comment by gregoriocanal** [comment]
Should we add a reference to ATNAm in this section?

**Comment by msmock** [comment]
You're right. The transaction is named and recommended to use WS Trust, but not explicitly defined. I'll improve the text.

**Comment by msmock** [comment]
changed from "defines a transaction" to "names a transaction".
