### ISSUE TITLE
Use of RFC7523 for client authentication

### ISSUE THREAD

**Issue by Martin-Rosner** [IHE/IT-Infrastructure#105]
For authentication, client_credentials grant is mandatory. To increase security, the use of RFC7523 for client authentication is preferred. Using this method, instead of sending the password over the line, creates a signed structure that can be validated.

**Comment by msmock** [comment]
We relied upon the Juli 2020 version of OAuth 2.1 which takes all the OAuth related security flaws into account. To keep things simple we took over the requirements of OAuth 2.1 for the client credential grant type, which is client_id and client_secret as minimum, if no other authentication method is used. Further I am not aware of an attack scenario for the authentication with client credentials in the client credential grant type (which is by the way not mandatory, since authorization code flow can be used as well).

**Comment by joostreuzel** [comment]
The SMART Backend Services is utilizing RFC7523 for service authentication.

RFC7523 uses a signed structure to authenticate the client (service) to the authorization service where OAuth2 client authentication uses a simple name/password combinations. For cryptographic point of view RFC7523 uses asymmetric encryption with public/private key pairs where the client authentication flow uses symmetric keys (the passwords). The use of public/private key pairs has the following benefits:
* The only knowledgeable source of private key is the client. A security breach of the server will not put those keys in the clear (with the corresponding impact on all clients).
* Through certificate chains a PKI can be created that simplifies key management. The authorization server needs to trust a certificate authority only and will as such trust all client certificates (with corresponding public keys) signed by that authority. This means that the server does not need to know all individual public keys (reducing management overhead). This also eases key rotation as this can be done without the involvement of the authorization server
* In the (unlikely) case an eavesdropper listens in on the communication between server and client the client’s key is not revealed. The used signed authentication structure has a limited life-time and therefore usability by the eavesdropper.

All-in-all it is more secure in case of server-side breaches.

**Comment by JohnMoehrke** [comment]
we discussed on the call today that we could
a) leave it as is, and add a declared open issue indicating that we are interested in public comment and trial implementation on the use 
b) add a named option for 7523 support. 

To do (b) we would need some help crafting the option, and what the text would need to say. Is it sufficient to have a simple paragraph explaining 7523, with no constraints?

@lcmaas what is your perspective on this issue?

**Comment by lcmaas** [comment]
@JohnMoehrke Referencing RFC 7523 is a good start but it is generally underspecified. We used RFC 7523 as one of the foundational components of [UDAP JWT-based Client Authentication](http://www.udap.org/udap-jwt-client-auth.html) and [UDAP Client Authorization Grants Using JSON Web Tokens](http://www.udap.org/udap-client-authorization-grants.html) and also defined how to tie-in to PKIX. @joostreuzel has listed some of the reasons why we did that.

So, at a minimum I would think IUA could note RFC 7523 as an option and leave it up to each AS how to operationalize that. You could also consider referencing the UDAP profiles as an alternative or as an example of how to implement RFC 7523.

**Comment by joostreuzel** [comment]
a reference to rfc7523 and 7522 as authorization grants is added in commit 701304dcea949a7ae362b7b9f901821d4874b16a ...
