### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/IT-Infrastructure#107]
Some typos that i found reading the supplement

**Comment by gregoriocanal** [comment]
section 34.1
Authorization Clients interact with the
Authorization Server to retrieve access token and incorporate them into HTTP RESTful
transactions to authorize access to resources on the Resource Servers.

should be
Authorization Clients interact with the
Authorization Server to retrieve access **tokens** and incorporate them into HTTP RESTful
transactions to authorize access to resources on the Resource Servers.

**Comment by gregoriocanal** [comment]
SECTION 34.1.1.2
If authorized, the Authorization Server provides a access token which
authorizes the client to retrieve data and documents from the Resource Server.

it should be 

If authorized, the Authorization Server provides an access token which
authorizes the client to retrieve data and documents from the Resource Server.

**Comment by gregoriocanal** [comment]
Section 34.2
The SAML Token Option enables integration of environments that use both, SAML
access token and the OAuth authorization infrastructure

it should be
The SAML Token Option enables integration of environments that use both, SAML
access token and the OAuth token, authorization infrastructure

**Comment by gregoriocanal** [comment]
Section 34.4.2.1
profile applies to use cases where a user authorizes an client application to access
health data behalf of the user using OAuth. Beyond other, relevant use cases are

should it be

profile applies to use cases where a user authorizes a client application to access
health data on behalf of the user using OAuth.


A healthcare professional uses a server hosted web application to access a patients
electronic health record (EHR) using RESTful transactions

should it be

A healthcare professionist uses a server hosted web application to access a patient's
electronic health record (EHR) using RESTful transactions

**Comment by gregoriocanal** [comment]
SECTION 34.4.1.2
Public clients just cannot
hide authentication data from the user rendering client authentication useless.

maybe it's better:
Public clients just cannot hide authentication data from the user, making client authentication useless.

**Comment by gregoriocanal** [comment]
SECTION 34.6

The XUA profile provides equivalent functionality for SOAP based transactions. Both
profiles, XUA and IUA define a transaction to incorporate a token to transactions
accessing protected data.

should it be
The XUA profile provides equivalent functionality for SOAP based transactions. Both
profiles, XUA and IUA define a transaction to incorporate a token into transactions
accessing protected data.

**Comment by gregoriocanal** [comment]
Section 3.71.4
According to new template this section should be titled Messages

**Comment by msmock** [comment]
Thanks. I updated all, but not the following proposal ...

Section 34.2
The SAML Token Option enables integration of environments that use both, SAML
access token and the OAuth authorization infrastructure

it should be
The SAML Token Option enables integration of environments that use both, SAML
access token and the OAuth token, authorization infrastructure

... since the current statement sounds correct to me.
