### ISSUE TITLE
Clarify use of (SAML) token formats vs grants

### ISSUE THREAD

**Issue by joostreuzel** [IHE/IT-Infrastructure#114]
continuation of discussion in #110 . Discussion summary inline below:

@joostreuzel : SAML tokens should be send to resource servers in the same way other tokens are send: as opaque bearer tokens.

@joostreuzel : IMHO, the specification should be more clear on the SAML token format. Is this format really necessary? If so, is it also possible to generate SAML tokens from e.g. the code credential flow. As such, I think SAML tokens are independent of SAML grants and should be treated a separate options.

@msmock : The saml option shall not be confused with the saml grant. That‘s right. IUA currently does not support the saml grant, but allows to use saml as client authentication. The saml token option is just for to use the usual XUA assertion as access token. And yes, we need the Saml token option in the Swiss  EPR.

@joostreuzel : The confusion with the SAML token arises from section 3.71.6.2. This section indicates the use of SAML2 grant types. The text mentions that RFC7522 is about "issuing and using SAML 2.0 assertions as access token", which is not true. RFC7522 merely speaks about using SAML Assertions as credentials (grants) to obtain an access token. Nothing is said about the access token structure.

@joostreuzel proposal:

- Introduce a separate section for the Get Authorization Token response. The request is different for different grants, but the response is the same in structure
- Move the SAML Assertion, as well as JWT token format to the message semantics section of the token response section
- Remove the section on token types from the Authorization Client. Tokens are opaque to clients. All tokens to be transmitted as Bearer tokens.
- Consequently: remove the use of IHE-SAML as Authorization header, use Bearer only (see #84)
- As part of the token handling behavior by the resource server refer to the token formats as described in the token response message and indicate the rules on how to deal with them.

**Comment by joostreuzel** [comment]
@msmock Question: In the Swiss EPR case (or more general) how do you deal with the token formats? Does the authorization server generate SAML-based access tokens for all resource servers, or does it switch between SAML and JWT formats depending on the intended audience of the token? 

Moreover, are the service endpoints that accept the SAML tokens expected to be fully IUA conformant, or are the SAML tokens primarily used to be compatible with existing systems that understand the SAML constructs only?

Reason for asking is that I'm wondering how service and server implementations in your case will deal with the different token formats, especially when configured in a specific environment with "legacy" systems.

**Comment by joostreuzel** [comment]
I took the liberty to include the suggestions as provided above in the document text. These have been  merged via #112.

**Comment by msmock** [comment]
> @msmock <https://github.com/msmock> : The saml option shall not be confused with the saml grant. That‘s right. IUA currently does not support the saml grant, but allows to use saml as client authentication. The saml token option is just for to use the usual XUA assertion as access token. And yes, we need the Saml token option in the Swiss EPR.
> 
The text only points to the section of RFC 7522 which defines the way the XUA token shall be encoded. If that’s confusing we must copy all of the text on SAML token encoding from RFC 7522 to our current working version. I thought about this when working on the document but decided not to change the reference to the encoding in RFC 7522, for better readability.

**Comment by msmock** [comment]
The IUA and MHD in the swiss EPR is currently in a trial implementation state. The service endpoints are IUA compliant and must support the JWT option. The reason to use the IUA SAML option is an advantage for the Authorization Clients (primary systems). 

In Switzerland the vendors already implemented the XUA Get Authorization Token transaction to get the XUA token and can incorporate that to RESTful calls. So far no Authorization server supports the SAML token option, but all Resource Server do (or can do with little effort), since by law they must support XUA and policy enforcement using a XUA token.

**Comment by joostreuzel** [comment]
> xt only points to the section of RFC 7522 which defines the way the XUA token shall be encoded. If that’s confusing we must copy all of the text on SAML token encoding from RFC 7522 to our current working version. I thought about this when working on the document but decided not to change the reference to the encoding in RFC 7522, for better reada

Understood. I will see that this logic is kept in my edits.

**Comment by joostreuzel** [comment]
Copied the serialization requirements from RFC7522 (with reference to the RFC) to the document in 50daa2c2a4077d04ed972c5d5bbf4e4d436cab3a
