### ISSUE TITLE
JWT Token as optional

### ISSUE THREAD

**Issue by joostreuzel** [IHE/IT-Infrastructure#115]
The IUA text describes now clearly the three options for token format and validation (JWT, SAML, or via introspect). JWT is required, the others are not as agreed.

Requiring JWT is rather constraining. It makes it much harder to connect to legacy systems that already have SAML or introspection support built in. Servers currently support the SAML or introspection would need to implement the JWT option which is a kind of superfluous.

The proposal is to allow implementations to choose one or more of these three options. The three options would become all optional, but there is an additional constraint that at least one of the three must be supported. Resource Servers that receive a token they cannot validate should simply refuse the request. 

I'm quite aware that this allows for variation: not all authorization servers and resources servers would be interoperable as they pick different options for token handling. However, this will create a drive for intelligent implementations. For example, Authorization Servers may choose a token format depending on the audience of the token. Generic server implementations may choose to support multiple options.

All-in-all it is a tradeoff: how easy should it be to include existing systems that already implement one of the (non-JWT) options, versus forcing interoperability by mandating a single way of token handling.

Perhaps this is something to discuss on a next call.

**Comment by msmock** [comment]
OAuth 2.1 draft says: 

"The token may denote an identifier used to retrieve the authorization information or may self-contain the authorization information in a verifiable manner (i.e., a token string consisting of some data and a signature)." Thus both is optional in OAuth 2.1 specification used in IUA.b and I don't see any reason to fall behind. 

To the best of my knowledge the JWT access token is used in the majority of real life projects. And we will use JWT  access token (as well as the XUA assertions) in the Swiss Electronic Patient Record project. Being forced to implement introspection is an unjustified restriction and a tradeoff and for the application of IUA.b in real life projects.

**Comment by joostreuzel** [comment]
As agreed in the IUA call on Thursday October 22nd, the idea is to make all three ways of token handling (JWT, SAML and Introspect) optional for now with the note that an implementation should pick at least one. Projects may impose additional restrictions. 

In addition, and as agreed, I will add an issue in which both the pros and cons of the JWT/Introspect options are mentioned. Allowing feedback to be gathered.

The suggested changes I will offer as pull-request shortly.
