### ISSUE TITLE
Promote SNIF whitepaper

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#130]
-White paper-
Configuration management of system-to-system interfaces that enable IHE profiles is burdensome within the healthcare enterprise. Interfaces are often manually configured, requiring trained integrators to: gather configuration properties, configure and test interoperability. The human element introduces the opportunity for errors, often typographical, that can be difficult to identify and correct. The increasing adoption of secure connectivity protocols complicates connectivity by adding additional connectivity properties, such as logging, and certificates.
This profile provides a consistent method to catalogue configuration properties for human and machine consumption during installation, upgrade and repair. This profile is a content profile that specifies properties and actors to create a “plug and play” like connectivity of interoperable systems.

Work item proposal

**Comment by JohnMoehrke** [comment]
Development repo https://github.com/IHE/SNIF

**Comment by snichols001** [comment]
Promoted in comp.protocols.dicom@googlegroups.com, pacs_admin@yahoogroups.com, zulip and UK Imaging Informatics Group on 2 September.
No additional comments received as of this comment.
