### ISSUE TITLE
Should IUA supplement carry updates to ATNA to support IUA+https?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#134]
Given all of the ATNA node-authentication transactions using TLS force client authentication by TLS, and Given that IUA authenticates the client system, Then should we provide in the IUA supplement the updates to ATNA that add a STX option for "IUA with server side https"?

**Comment by JohnMoehrke** [comment]
Without this ATNA Option, any grouping with ATNA would require mutual-authenticated-TLS, in addition to the IUA token mechanism.

**Comment by msmock** [comment]
We must take into account, that Node Authentication by definition authenticates the network node the Authorization client application is running in, but not the client application. And, that client authentication is not required in the authorization code flow, since the user explicitly authorizes the application. This is quite important if it comes to mHealth clients operated on mobile devices.

**Comment by JohnMoehrke** [comment]
@msmock to be specific. the ATNA Node Authentication is mutual-authenticated-TLS, not just server side TLS that is more classically used with browsers and applications in https. Thus to use the ATNA profile today, would require that the client application also be issued an TLS Client certificate that it uses in addition to the OAuth mechanisms... Hence why I think it is important to address this,.

**Comment by msmock** [comment]
I don’t understand the context, since IUA.b does not require Authorization Clients to be grouped with ATNA, or did I miss something?

**Comment by JohnMoehrke** [comment]
the first profile that projects bring in is ATNA as it brings in network encryption and audit logging... they then add a profile from EUA, XUA, or IUA... In the case of grouping with IUA, the result today would be that the app would need a TLS certificate for the required ATNA secure communications, and also OAuth credentials. This is not what the normal OAuth community expects. The normal OAuth community expects simple https, which only put TLS server side authentication. This configuration does not exist in ATNA today. I am recommending that it should be an ATNA configuration, and that the IUA supplement is the logical supplement to add this option to ATNA.

**Comment by JohnMoehrke** [comment]
This option could be recommended in IUA, but IUA could be silent. IUA can be used with mutual-authenticated-TLS, it is just not normal. 
This option in ATNA would mandate IUA be used for the client authentication that is not covered by server-authenticated-TLS
