### ISSUE TITLE
IUA: Review comments

### ISSUE THREAD

**Issue by joostreuzel** [IHE/IT-Infrastructure#136]
Based on a overall review of the document a number of todo's can be formulated:

- [x] consistent use of client_id iso clientID, etc.
- [x] update to latest version of referenced specifications
- [x] consistent capital usage in terms
- [x] iat-field in JWT token is mandatory according to JWT specification
- [x] ihe-iua JWT extension example contains unspecified resource_id field
- [x] Audit record required for authorization failure at resource server?
- [x] a series of minor textual fixes (duplicate words, etc.)

**Comment by JohnMoehrke** [comment]
audit is now issue #91
