### ISSUE TITLE
Vocabulary for IUA in CapabilityStatement.rest.security

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#30]
We need to define one or more vocabulary values to be used in the server CapabilityStatement to indicate that the rest server is using IUA profile. I have asked Grahame if IHE should manage a small codeSystem, or should just ask HL7/FHIR to create one or more vocabulary values for us. His opinion is that we should just ask HL7/FHIR to create them.

So, we need to determine what we would like these vocabulary values and descriptions would be. Do we need just one for IUA, or do we need more than one to represent the options within IUA?

**Comment by walcovanloon** [comment]
I think we should strive for one code for IUA; a bit dependent on the outcome of the upcoming discussion on the SAML token option.

**Comment by JohnMoehrke** [comment]
I will create a FHIR codeSystem to hold IHE defined security types for use in CapabiltyStatement.rest.security.service

It will initially contain
* ATNA (just start with base, likely needs to include some of the ATNA options for distinction)
* IUA
* XUA

Will also include a pull request with my recommended inserted narrative text for IUA profile.

**Comment by JohnMoehrke** [comment]
I did provide, did you integrate that into the text?
