### ISSUE TITLE
Automate doc conversion

### ISSUE THREAD

**Issue by JurrianFahner** [IHE/IT-Infrastructure#31]
It would be nice that there is a build script to build the doc and converts it to docx and pdf automatically. And that these will be available in a release bundle. 

We could use for instance github actions for that. 

Can I offer my help to make this happen?

**Comment by JohnMoehrke** [comment]
we have a three different approaches being prototyped.
a) Using Markdown as the source publishing to html and PDF -- HIE-Whitepaper
b) Using html as source publishing as html and supporting PDF output -- Final Text Technical Framework
c) FHIR Implementation Guide Publisher
