### ISSUE TITLE
IUA client shouldn't have say in access token type

### ISSUE THREAD

**Issue by lcmaas** [IHE/IT-Infrastructure#50]
In Main Flow 1 of Incorporate Access Token, current text says "The authorization token may be an SAML token, a JWT Bearer token, or another access token type that is mutually agreed between Client, Resource Service and the token source." 

The access token issued by the token source is not generally intended to be understood by the client and should generally be treated as an opaque string by the client to pass along to the resource server.

Recommendation:
remove "Client" from the list

**Comment by msmock** [comment]
refactored the relevant parts as discussed during the July F2F meeting.
