### ISSUE TITLE
Unclear statement in delegation and authority

### ISSUE THREAD

**Issue by msmock** [IHE/IT-Infrastructure#61]
Section 34.4.22 Line 405 in IUA.b, Rev.1.2 from September 21, 2019, states: 
_Users may delegate authority to:_

It is not obvious to me, what is meant with authority. 

In addition, one of the core concepts of OAuth 2.0 is, that the resource owner (user) explicitly authorizes applications to act on behalf by confirming the access right in a dialog.

**Comment by JohnMoehrke** [comment]
is this closed?
