### ISSUE TITLE
IUA: create overview of involved standards

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#74]

**Comment by msmock** [comment]
Luckily the IETF published a consolidated version of the OAuth Authorization Framework (https://oauth.net/2.1/) which consolidates the best practices and all the RFC which have been published in addition to the 2.0 version. I updated the references in the IUA.b working version to OAuth 2.1 draft version and the references therein. The issue should be fixed from my point of view.

**Comment by JohnMoehrke** [comment]
so, should this be closed?
