### ISSUE TITLE
IUA should use "Bearer" scheme to be compatible with RFC 6750

### ISSUE THREAD

**Issue by msmock** [IHE/IT-Infrastructure#84]

**Comment by msmock** [comment]
I converted this issue from a note posted by Walco to be discussed.

**Comment by joostreuzel** [comment]
In the latest IUA edits, solely Bearer tokens are used...

**Comment by walcovanloon** [comment]
This issue I addressed in the first edits indeed

**Comment by joostreuzel** [comment]
Closing as all tokens are treated as Bearer tokens in the current version.
