### ISSUE TITLE
Open Discussion IHE issue 1: This profile does not specify the internal structure of "client_id".

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#89]
Issue 1: This profile does not specify the internal structure of "client_id". This is a major concern for operations and security management. But, OAuth does not provide a full specification for client_id. It just specifies its purpose. DICOM's equivalent information attributes are: Manufacturer, Model, Software Versions, and Serial Number. The OAuth client ID must identify the device, the application (including any necessary version information), the particular instance, and any other information needed to identify the client application uniquely. Registration of clients is a significant operational and security problem that is being postponed until there is more experience with problems in the field and reasonable solutions. There is known danger from spoofing of client_id. At this time, the method for assignment of client_id is not included in the profile. In the field there are a variety of methods being tried. Many depend upon physical distribution methods or out of band communications to manage the authentication problems.

**Comment by JohnMoehrke** [comment]
Can we not force certificate based client authentication, where the certificate could contain this app metadata?
@lcmaas is there a common solution to this?

**Comment by lcmaas** [comment]
re: yes, if the authn is certificate-backed, the certificate can contain some relevant metadata about the app and its operator, and unique cert attributes can be used as a substitute for a client_id (e.g. iss+s/n). Note, however, that "Standard" X.509 extensions may not be well suited for many app-specific attributes; I like JWTs bound the the certificate for this.

re: client_id: Note that client_id is assigned by the resource server's AS and used to bind the client registration step to subsequent client authentication when token endpoint requests are submitted to the resource server's AS. IIRC, the draft IUA workflow does not require registration and the construction of the access token takes place entirely on the client side (i.e. it is not generated by the data holder's AS), so this effectively skips the workflow steps that require the client_id in the first place. Obviously, this won't work for other flows (like authorization_code).

**Comment by JohnMoehrke** [comment]
I would like to see an option defined for certificate authentication of app registration. I would agree that this should not be minimal support.

@lcmaas can you provide some links to specifications regarding your proposal for certificate based app registration? (I did say that right, correct?)

**Comment by lcmaas** [comment]
@JohnMoehrke  yes UDAP Trusted Dynamic Client Registration is certificate-backed.

The specification is here: http://www.udap.org/udap-dynamic-client-registration.html.

In reviewing the updates to the IUA draft, I find that there is still a disconnect between the current IUA draft and the typical OAuth deployments for healthcare use cases that I am familiar with, especially when it comes to app registration and client_ids. The IUA actor labeled "Authorization Server" doesn't appear to be primarily representing the resource server's interests, but appears to be more closely coupled with the client. (If not, how does the AS know what data to populate in the assertion about purpose of use, consent, etc.?) It seems to me like the IUA-AS is based on the entity in XUA that generates the SAML assertions that a requestor includes in its requests. At least for the privileged app flows with client_credentials. This helps explain why typical OAuth 2 app registration and client_id management are not easily worked into this model.

UDAP works these types of assertions into OAuth 2 flows by adapting the assertion framework in RFCs 7521-7523. I'd be happy to discuss further if the IUA stakeholders are interested in aligning IUA more closely with UDAP. Though this is a non-trivial change to IUA flows, it might be possible to include by reference as an alternative flow. See, for example, section 5.2 of [UDAP Client Auth Grants](http://www.udap.org/udap-client-authorization-grants.html). Note that in UDAP, the entity that creates the Authorization Tokens for the client is called the "Client Token Service" (and is separate from the Authorization Server that represents the responder).

**Comment by JohnMoehrke** [comment]
I am not clear what the action is that is left to do on this one. Will this become an open issue? Is there clarifications we need to address in the text? Has other pull requests resolved some of this?
