### ISSUE TITLE
Open Discussion IUA Issue 2: JWT token vs other token types

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#90]
Issue 2: This profile mandates support for JWT token format. It has an XUA SAML Option defined by IHE for ease of integration with the IHE WS-Security environment. You may also use other token formats as part of a deployment.

**Comment by JohnMoehrke** [comment]
I think the tendency is to move toward introspection to get at the attributes of the token... right?
@lcmaas @walcovanloon @mascanc ?

**Comment by lcmaas** [comment]
Typically,  JWT (or SAML) tokens are used so that the resource server can validate the token cryptographically without requiring introspection. But yes, if required, you can use introspection to get additional info that isn't in the token or to confirm that it hasn't been revoked (e.g., for long-lived tokens).  Since the token was generated by a client-side server, you'd also have to define how the resource server authenticates to that server (since introspection should be a protected service).

**Comment by joostreuzel** [comment]
The reasoning above is why I would make introspection support mandatory and the structured token formats (JWT, SAML) optional. Introspect will work for all token formats in all situations. A resource server simply does not need to understand the token format. This means that a server that has not been designed for XUA SAML token support can still work with such tokens as it would simply obtain the token contents through introspect.

JWT and/or (XUA) SAML tokens, or other structured token formats are IMHO optimizations. If a resource server knows that the tokens are in one of those formats, it can omit the introspect step and work with the claims derived from those tokens directly. 

There are a few benefits and drawbacks to introspect:
* (plus) With introspect the only party that needs to understand the token format is the authorization server. Resource servers become token format agnostic and will be able to deal with all types of tokens supported by their authorization server. It even allows simultaneous use of different token formats (XUA _and_ JWT) in the same deployment, as long as the authorization server is able to handle them. In a sense, token verification and parsing is delegated by the resource server to the authorization server.
* (plus) An Authorization Server may apply complex logic during the introspect call, providing an additional level of authorization models. This may range from token revocation logic to eg. time-based constraints for a subset of the token audience. Such complex logic is hard to encode in structured (JWT/SAML) tokens and cannot be expected to be implemented by generic resource servers.
* (plus) Introspect allows the use of opaque identifiers as  tokens (so-called reference tokens) that do not contain any privacy sensitive information (such as consents, patient ids, etc.). Moreover, such tokens would also not contain any data usable by hackers (such as used scopes, audiences, etc.).
* (plus) Introspect allows for (reference) token formats that are a lot smaller than JWT or SAML tokens, avoiding conflict with web servers or routers that have maximum header lengths. This especially holds when the JWT would contain a lot of extension claims.
* (plus) Introspect allows token evaluations to be tuned to specific resource servers, hiding scopes and other information that are not essential to that resource server.  Introspect of the same token may deliver different results for different resource servers.
* (minus) Compared to structured tokens, introspect comes with communication overhead between resource servers and authorization servers, though much of this overhead may be reduced by caching introspect results
* (minus) Introspect requires that resource servers will need to be provided with credentials, which introduces administrative overhead. That said, most authorization servers will already have resource servers listed for use in their authorization models, as clients will typically get access to only a few configured resource servers (as indicated in the audience claim).

Given this, I would suggest to make introspect support non-optional. It provides the biggest level of interoperability, while giving the biggest flexibility in terms of supported authorization models. JWT and SAML support would become optional, perhaps even recommended (JWT in case of more simple authorization models, SAML in case of compatibility with XUA).

**Comment by joostreuzel** [comment]
Note: #115 may be a duplicate of this topic.
