### ISSUE TITLE
Confusing language in "Background on the problem environment"

### ISSUE THREAD

**Issue by GumptionWare** [IHE/IT-Infrastructure#93]
In this bullet/paragraph:

- IT administrators are more willing to run their own internal authentication and authorization servers, but want to use off the shelf software and want the option to outsource these services. **They are more likely to separate authentication from authorization than end user systems.** Authentication issues are closely related to HR activities like hiring and firing. Authorization issues are related to patient and work assignments. These are controlled by different parts of the organization and have different process dependencies.

... I have bolded the sentence "They are more likely to separate authentication from authorization than end user systems" to show it in context.

Should this sentence be "They are more likely to separate authentication from authorization **for** (or **with**) end user systems"? 

If not, please explain what this sentence is intended to convey, and I'll help clarify the wording.

**Comment by msmock** [comment]
I took this sentence from the working versions when I started to work on IUA. I'm also not happy with the statements at all. Maybe we can remove it? This should be discussed in the meeting this week.

**Comment by msmock** [comment]
I'll remove the bullet point, since it is not clear what the statement actually means.
