### ISSUE TITLE
Capability statement required for non-FHIR Resource Server

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/IT-Infrastructure#94]
Section 34.1.1.3 states:

"Resource Server SHALL declare support for IUA in the capabilities endpoint using the element CapabilityStatement.rest.security. and the code "IUA" at system canonical URL "http://profiles.ihe.net/fhir/ihe.securityTypes/CodeSystem/securityTypes"."

Does this requirement hold even when the Resource Server does not expose FHIR APIs? It seems FHIR might be a common use case for IUA but IUA should be generic enough to work in any RESTful environment. Seems like it would be rather odd and possibly an undue burden to apply this requirement to a server that is RESTful but not FHIR.

**Comment by kwboone** [comment]
That’s about ten lines of code for minimal support.

**Comment by lcmaas** [comment]
Why not add to start of sentence, "If the resource server is a FHIR Server, then the..."

**Comment by joostreuzel** [comment]
Agree with @slagesse-epic of trying to avoid IUA to become dependent on FHIR as it should be usable for any type of REST endpoint. In commit 50daa2c2a4077d04ed972c5d5bbf4e4d436cab3a (to be merged still) I added the clause that this is mandatory behavior for FHIR-based resource servers only. Other servers may do so as well, but it isn't mandatory.

Not the same, but related: Issue #111 contains a proposal that allows Authorization Clients to figure out what type of grants, tokens, endpoints, options are supported by an Authorization Server. This eases configuration at the client side.

A FHIR server's capability statement may point to the authorization server and this meta-data document will tell the client where and how to obtain the access tokens. Not sure though if such a thing would ever be used in practice as clients are most likely preconfigured to work with IUA and a specific Authorization Server. Moreover, clients typically need to be pre-registered at that AS for authorization to work...

**Comment by JohnMoehrke** [comment]
agreed. the capability statement stuff was always intended to be ONLY for when use with a FHIR based use-case. The main reason to have this is to enable automation. A client can see this declaration in a servers metadata endpoint and thus know what they need to do administratively next. It was not intended to fully automate. It is also there as SMART has a code for use when SMART is used, so it is equal feature.

**Comment by joostreuzel** [comment]
Was wondering if we need to add something to "IHE Appendix Z on HL7® FHIR" on this topic?

**Comment by JohnMoehrke** [comment]
> Was wondering if we need to add something to "IHE Appendix Z on HL7® FHIR" on this topic?

@joostreuzel I looked at the Appendix Z and don't find anything specific to add. This appendix already points at IUA, so I would expect any IUA specifics would not be included in Appendix Z. This said, I am happy to be given a specific suggestion on what to add to Appendix Z.
