### ISSUE TITLE
Some Section Headers Too Small

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/IT-Infrastructure#95]
Some section headers, such as 3.71.4.1.1, appear smaller than the font used for normal paragraph text. This makes them easy to miss (especially when they appear next to images) and thus it makes it difficult for the reader to realize they are moving on to a new section.

**Comment by JohnMoehrke** [comment]
I don't plan on solving this one before Public Comment phase, will look again for resolving by Trial Implementation publication
