### ISSUE TITLE
JSON Web Token Example Wrong?

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/IT-Infrastructure#96]
Section 3.72.8.1:

A non normative example of the access token incorporation to a RESTful transaction is as follows:

GET /example/url/to/resource/location 
HTTP/1.1
**Authorization: IHE-SAML fFBGRNJru1FQd\[...omitted for brevity...\]44AzqT3Zg**
Host: examplehost.com

This looks like a copy of the SAML token option rather than an example of the JSON Web Token option.

**Comment by msmock** [comment]
Thank you for the finding. I‘ll correct it.

Regards, 
Martin

**Comment by msmock** [comment]
Fixed.
