### ISSUE TITLE
unclear bullet on "Background on the problem environment" section

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/IT-Infrastructure#98]
"IT administrators are more willing to run their own internal authentication and
authorization servers, but want to use off the shelf software and want the option to
outsource these services. **They are more likely to separate authentication from
authorization than end user systems.** Authentication issues are closely related to
HR activities like hiring and firing. Authorization issues are related to patient and
work assignments. These are controlled by different parts of the organization and
have different process dependencies."

I suggest to modify the bold text.

**Comment by msmock** [comment]
I took this from the working draft without a change, but I am also not happy with the statements in the text. Do you have a suggestion to improve?
